# Dapper config file
---
name: Mark Benson
url: http://markbenson.io/
ignore :
    - "^\."
    - "^_"
    - "^design$"
    - "^README.md$"
    - "^Makefile$"
copyright: "[% use date %]&copy; Mark Benson [% date.format(date.now, '%Y') %]"
cv:
    title: Mark Benson, Chief Technology Officer
    summary: Accomplished C-level technology leader. Experienced in strategic, operational, and financial management of cross-functional teams in highly-competitive markets. Successful track record of defining and realizing pragmatic product strategies to meet the requirements of complex enterprises across multiple functions and verticals. Strong interpersonal and formal communication skills.
    skills:
        - Technology Leadership
        - Product Management
        - Strategic Planning
        - Intellectual Property Portfolio Management
        - Software Development Life Cycle
        - Information Security
        - Competitive Strategy
    strengths:
        - Learner
        - Restorative
        - Individualization
        - Achiever
        - Intellection
    personality: INFJ-A (Advocate)

