# Dapper config file
---
name: Mark Benson
author: Mark Benson
url: https://markbenson.io/
ignore:
    - ^\.
    - ^_
    - ^design$
    - ^README.md$
    - ^Makefile$
    - .DS_Store
    - access.log
copyright: "[% use date %]&copy; [% site.author %] 2001 - [% date.format(date.now, '%Y') %]"
cv:
    title: Mark Benson
    subtitle: Technology Executive
    summary: Accomplished C-level technology executive with expertise in strategic, operational, and financial management of businesses primarily driven by software and systems products and services. Proven ability to lead cross-functional teams and execute complex product strategies that drive meaningful outcomes. Strong interpersonal and formal communication skills.
    skills:
        - Product Management
        - Software Engineering
        - Strategic Planning
        - Competitive Strategy
        - Organizational Behavior
    strengths:
        - Learner
        - Restorative
        - Individualization
        - Achiever
        - Intellection
    personality: INFJ-A (Advocate) / DiSC SC (Steady/Conscientious) / Enneagram Type 3 (Achiever)
    about: Mark Benson is Head of <a href="http://smartthings.com">Samsung SmartThings</a>, author of <a href="/stmes/">The Art of Software Thermal Management for Embedded Systems</a>, and is a regular speaker and writer on leadership, organizational behavior, and the future of the smart home.
    statement: I'm Mark Benson, Head of <a href="http://smartthings.com">Samsung SmartThings</a>. I am passionate about creating products that deliver meaningful experiences for users and building diverse teams that are high-performing, hyper-collaborative, and customer-obsessed.
