# Dapper config file
---
name: Mark Benson
url: http://markbenson.io/
ignore :
    - "^\."
    - "^_"
    - "^design$"
    - "^README.md$"
    - "^Makefile$"
    - ".DS_Store"
    - "access.log"
copyright: "[% use date %]&copy; Mark Benson 2001 - [% date.format(date.now, '%Y') %]"
cv:
    title: Mark Benson
    subtitle: Product Management & Software Engineering Leader
    summary: Accomplished C-level technology leader. Experienced in strategic, operational, and financial management of cross-functional teams in highly-competitive markets. Successful track record of defining and realizing pragmatic product strategies to meet the requirements of complex enterprises across multiple functions and verticals. Strong interpersonal and formal communication skills.
    skills:
        - Strategic Planning
        - Product Management
        - Software Engineering Leadership
        - Information Security
        - Competitive Strategy
        - Organizational Behavior
    strengths:
        - Learner
        - Restorative
        - Individualization
        - Achiever
        - Intellection
    personality: INFJ-A (Advocate)
    about: Mark Benson is Head of Product & Engineering at <a href="http://smartthings.com">Samsung SmartThings</a>. Mark is the author of <a href="/stmes/">The Art of Software Thermal Management for Embedded Systems</a> and is a regular speaker and writer on the intersection of technology, business, and society as it relates to strategic planning, product management, competitive strategy, software engineering leadership, information security, and organizational behavior.
    personal-statement: I'm passionate about creating great experiences. I love creating consumer products that deliver meaningful and delightful user experiences, and building teams and culture that are happy, healthy, high-performing, and diverse.

